{
  "belly":"http://www.flaticon.com/free-icon/pregnant_10975",
  "athlete":"http://www.flaticon.com/free-icon/group-of-men-running_10603",
  "runners":"http://www.flaticon.com/free-icon/group-of-men-running_10603",
  "drink": "http://www.flaticon.com/free-icon/glass-of-drink_66287",
  "road": "http://www.flaticon.com/free-icon/road-perspective_53164",
  "alligator": "http://www.flaticon.com/free-icon/australian-alligator_65685",
  "car": "http://www.flaticon.com/free-icon/sedan-car-side-view_48301",
  "peach": "http://www.flaticon.com/free-icon/peach_52905",
  "soldier": "http://www.flaticon.com/free-icon/male-holding-armalite-gun_27795",
  "people": "http://www.flaticon.com/free-icon/users-group_32441",
  "baby": "http://www.flaticon.com/free-icon/crawling-baby-silhouette_43890",
  "sphere": "http://www.flaticon.com/free-icon/earth-globe-with-parallel-horizontal-lines-pattern_44574",
  "thief":"http://www.flaticon.com/free-icon/thief_10925",
  "flag":"http://www.flaticon.com/free-icon/flag-undulate_13255",
  "barrels":"http://www.flaticon.com/free-icon/cask_66517",
  "cave":"http://www.flaticon.com/free-icon/mountain-cave_2151",
  "sink":"http://www.flaticon.com/free-icon/sink-of-bathroom_15222",
  "bayonet":"http://www.flaticon.com/free-icon/strong-knife_62614",
  "beach":"http://www.flaticon.com/free-icon/beach-umbrella-black-silhouette_34234",
  "beans":"http://www.flaticon.com/free-icon/coffee-bean-for-a-coffee-break_31082",
  "dog":"http://www.flaticon.com/free-icon/running-dog-silhouette_47203",
  "cattle":"http://www.flaticon.com/free-icon/cow-silhouette_62470",
  "beetle":"http://www.flaticon.com/free-icon/spotted-beetle-insect-of-a-garden_47456",
  "berries":"http://www.flaticon.com/free-icon/strawberry_52876",
  "tree":"http://www.flaticon.com/free-icon/royal-oak-homes-logo-of-tree-silhouette_36470",
  "priest":"http://www.flaticon.com/free-icon/pastor-silhouette-with-cross_33850",
  "flower":"http://www.flaticon.com/free-icon/japanese-flower_12644",
  "ship":"http://www.flaticon.com/free-icon/military-boots-with-lace-for-female_24936",
  "rocks":"http://www.flaticon.com/free-icon/faraglioni-rocks_679",
  "wine":"http://www.flaticon.com/free-icon/wine-glasses_65155",
  "breakfast":"http://www.flaticon.com/free-icon/snacks-sign_61320",
  "house":"http://www.flaticon.com/free-icon/house-frontal-building_8811",
  "ground":"http://www.flaticon.com/free-icon/shovel-and-ground_27562",
  "church":"http://www.flaticon.com/free-icon/church_1845",
  "Q45":"http://www.flaticon.com/free-icon/triangular-shovel-with-liquid-concrete_46417",
  "money":"http://www.flaticon.com/free-icon/dollar-coins_50959",
  "hen":"http://www.flaticon.com/free-icon/chicken-ios-7-interface-symbol_17864",
  "city":"http://www.flaticon.com/free-icon/modern-city-towers-buildings-group_46409",
  "dirt":"http://www.flaticon.com/free-icon/shovel-and-ground_27562",
  "cook":"http://www.flaticon.com/free-icon/female-cook_65589",
  "clothes":"http://www.flaticon.com/free-icon/dress_26487",
  "couch":"http://www.flaticon.com/free-icon/sofa-with-armrest_64634",
  "cross":"http://www.flaticon.com/free-icon/black-cross_12174",
  "woman":"http://www.flaticon.com/free-icon/business-woman_33674",
  "plate":"http://www.flaticon.com/free-icon/fork-knife-and-plate_1328",
  "USB":"http://www.flaticon.com/free-icon/memory-stick_32091",
  "pc":"http://www.flaticon.com/free-icon/pc-computer-with-monitor_34100",
  "videogame":"http://www.flaticon.com/free-icon/gamepad-with-3-buttons_13973",
  "robot":"http://www.flaticon.com/free-icon/robot-with-flexible-arms-and-legs_48644",
  "Q60":"http://www.flaticon.com/free-icon/cell-phone_191",
  "laptop":"http://www.flaticon.com/free-icon/laptop-open-frontal-view-with-buttons-and-blank-screen_36223",
  "touchpad":"http://www.flaticon.com/free-icon/hand-touching-tablet-screen_64828",
  "floppy":"http://www.flaticon.com/free-icon/floppy-disc-vintage-storage-disk-format-save-interface-button_13842",
  "programmer":"http://www.flaticon.com/free-icon/desktop-computer_5088",
  "router":"http://www.flaticon.com/free-icon/wifi-router_65376",
  "ram":"http://www.flaticon.com/free-icon/random-access-memory-chip_18033",
  "nuclear energy":"http://www.flaticon.com/free-icon/atom_329",
  "chips":"http://www.flaticon.com/free-icon/fries-pack_62497",
  "cup":"http://www.flaticon.com/free-icon/coffee-cup-on-a-plate-black-silhouettes_25699",
  "socket":"http://www.flaticon.com/free-icon/wall-socket_62866",
  "recycling":"http://www.flaticon.com/free-icon/eraser_65980",
  "shop":"http://www.flaticon.com/free-icon/shop_48363 ",
  "man":"http://www.flaticon.com/free-icon/business-man_33551",
  "door":"http://www.flaticon.com/free-icon/open-exit-door_59801",
  "pigeon":"http://www.flaticon.com/free-icon/pigeon-bird-shape_47092",
  "pipe":"http://www.flaticon.com/free-icon/pipes-tubes-angle_46254",
  "drugs":"http://www.flaticon.com/free-icon/medical-drugs_52440",
  "king":"http://www.flaticon.com/free-icon/king-in-his-throne_10652",
  "factory":"http://www.flaticon.com/free-icon/factory_31495",
  "violin":"http://www.flaticon.com/free-icon/violin-silhouette_26560",
  "fireplace":"http://www.flaticon.com/free-icon/fireplace-with-fire-flames-heating-home_47472",
  "frog":"http://www.flaticon.com/free-icon/frog-head-frontal-outline_58791",
  "marijuana":"http://www.flaticon.com/free-icon/marijuana-leaf_66106",
  "grave":"http://www.flaticon.com/free-icon/halloween-cemetery_12010",
  "snake":"http://www.flaticon.com/free-icon/snake-of-brazil_47135",
  "rabbit":"http://www.flaticon.com/free-icon/rabbit-ios-7-interface-symbol_17833",
  "teacher":"http://www.flaticon.com/free-icon/teach_4413",
  "branch":"http://www.flaticon.com/free-icon/one-branch-with-leaves_13349",
  "cop":"http://www.flaticon.com/free-icon/policeman_1259",
  "ocean":"http://www.flaticon.com/free-icon/beach-view-of-sea-sun-and-seagulls-couple_34940",
  "artist":"http://www.flaticon.com/free-icon/painter-painting_10579",
  "doctor":"http://www.flaticon.com/free-icon/md_37856",
  "store":"http://www.flaticon.com/free-icon/shopping-cart-of-checkered-design_34627",
  "cart":"http://www.flaticon.com/free-icon/shopping-cart-of-checkered-design_34627",
  "parking sp":"http://www.flaticon.com/free-icon/parking-for-disabled-persons-sign_34977 ",
  "cleaner":"http://www.flaticon.com/free-icon/frontal-standing-man-silhouette_10522",
  "soccer":"http://www.flaticon.com/free-icon/soccer-player-silhouette_48181",
  "microbes":"http://www.flaticon.com/free-icon/virus-through-magnifying-glass_63412",
  "moth":"http://www.flaticon.com/free-icon/butterfly_66278",
  "rubbish":"http://www.flaticon.com/free-icon/rubbish-can_62991",
  "bat":"http://www.flaticon.com/free-icon/baseball-bat-silhouette_37689",
  "knife":"http://www.flaticon.com/free-icon/strong-knife_62614",
  "mouse":"http://www.flaticon.com/free-icon/mouse-pet_42158",
  "boot":"http://www.flaticon.com/free-icon/military-boots-with-lace-for-female_24936",
  "bench":"Made By Author",
  "dunes":"Made by Author"
}
